[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn robotics_planner.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always" 